{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  # labels
  {{- if .Values.labels }}
  labels:
    {{- include "labels" . | indent 4 }}
  {{- end }}
  # namespace
  namespace: {{ .Values.namespace | default "default" }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
